# -*- coding: utf-8 -*-

import sys
import os
import subprocess

exit_code = subprocess.call(
    ['C:\\Users\\raula\\AppData\\Local\\Programs\\Python\\Python313\\python.exe', '-W', 'ignore', 'C:\\Users\\raula\\AppData\\Local\\Programs\\Python\\PYTHON~1\\Lib\\SITE-P~1\\nuitka\\build\\INLINE~1\\bin\\scons.py', '--quiet', '-f', 'C:\\Users\\raula\\AppData\\Local\\Programs\\Python\\PYTHON~1\\Lib\\SITE-P~1\\nuitka\\build\\BACKEN~1.SCO', '--jobs', '8', '--warn=no-deprecated', '--no-site-dir', 'nuitka_src=C:\\Users\\raula\\AppData\\Local\\Programs\\Python\\PYTHON~1\\Lib\\SITE-P~1\\nuitka\\build', 'python_version=3.13', 'python_prefix=C:\\Users\\raula\\AppData\\Local\\Programs\\Python\\Python313', 'experimental=', 'debug_modes=', 'deployment=false', 'no_deployment=', 'console_mode=force', 'noelf_mode=true', 'cpp_defines=_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1', 'target_arch=x86_64', 'module_mode=false', 'dll_mode=false', 'exe_mode=true', 'standalone_mode=true', 'onefile_mode=true', 'gil_mode=true', 'source_dir=.', 'nuitka_python=false', 'debug_mode=false', 'debugger_mode=false', 'python_debug=false', 'full_compat=false', 'trace_mode=false', 'file_reference_mode=runtime', 'compiled_module_count=17', 'result_exe=C:\\Users\\raula\\Desktop\\SIDEJI~1\\LAUNCH~1.DIS\\SideJITServer-windows-x86_64.exe', 'frozen_modules=154', 'python_sysflag_no_site=true'],
    env={'ALLUSERSPROFILE': 'C:\\ProgramData','APPDATA': 'C:\\Users\\raula\\AppData\\Roaming','COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files','COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files','COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files','COMPUTERNAME': 'DESKTOP-UT8HHNG','COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe','DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData','FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer','FPS_BROWSER_USER_PROFILE_STRING': 'Default','HOMEDRIVE': 'C:','HOMEPATH': '\\Users\\raula','LOCALAPPDATA': 'C:\\Users\\raula\\AppData\\Local','LOGONSERVER': '\\\\DESKTOP-UT8HHNG','NUMBER_OF_PROCESSORS': '8','ONEDRIVE': 'C:\\Users\\raula\\OneDrive','OS': 'Windows_NT','PATH': 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Users\\raula\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\raula\\AppData\\Local\\GitHubDesktop\\bin;D:\\Microsoft VS Code\\bin','PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC','PROCESSOR_ARCHITECTURE': 'AMD64','PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel','PROCESSOR_LEVEL': '6','PROCESSOR_REVISION': '8e0a','PROGRAMDATA': 'C:\\ProgramData','PROGRAMFILES': 'C:\\Program Files','PROGRAMFILES(X86)': 'C:\\Program Files (x86)','PROGRAMW6432': 'C:\\Program Files','PROMPT': '$P$G','PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules','PUBLIC': 'C:\\Users\\Public','PYTHONHASHSEED': '0','SESSIONNAME': 'Console','SYSTEMDRIVE': 'C:','SYSTEMROOT': 'C:\\WINDOWS','TEMP': 'C:\\Users\\raula\\AppData\\Local\\Temp','TMP': 'C:\\Users\\raula\\AppData\\Local\\Temp','USERDOMAIN': 'DESKTOP-UT8HHNG','USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-UT8HHNG','USERNAME': 'raula','USERPROFILE': 'C:\\Users\\raula','WINDIR': 'C:\\WINDOWS','ZES_ENABLE_SYSMAN': '1','NUITKA_PYTHON_EXE_PATH': 'C:\\Users\\raula\\AppData\\Local\\Programs\\Python\\Python313\\python.exe','NUITKA_PACKAGE_DIR': 'C:\\Users\\raula\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\nuitka','NUITKA_CACHE_DIR_DOWNLOADS': 'C:\\Users\\raula\\AppData\\Local\\Nuitka\\Nuitka\\Cache\\DOWNLO~1','_NUITKA_ONEFILE_CHILD_GRACE_TIME_INT': '5000','_NUITKA_BUILD_DEFINITIONS_CATALOG': '_NUITKA_ONEFILE_CHILD_GRACE_TIME_INT,_NUITKA_BUILD_DEFINITIONS_CATALOG','NUITKA_QUIET': '0'},
    shell=False
)