name: Compile Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka ordered-set zstandard jinxed
        
    - name: Install project dependencies
      run: |
        if (Test-Path SideJITServer-main/requirements.txt) {
          pip install -r SideJITServer-main/requirements.txt
        } else {
          Write-Host "No requirements.txt found, installing basic dependencies"
          pip install click
        }
        
    - name: Download WinTUN
      run: |
        $wintunUrl = "https://www.wintun.net/builds/wintun-0.14.1.zip"
        $wintunZip = "wintun.zip"
        try {
          Invoke-WebRequest -Uri $wintunUrl -OutFile $wintunZip
          Expand-Archive -Path $wintunZip -DestinationPath "."
          Write-Host "WinTUN downloaded successfully"
        } catch {
          Write-Host "WinTUN download failed, continuing without it"
        }
        
    - name: Show installed packages
      run: |
        pip list
        
    - name: Compile with Nuitka
      run: |
        python -m nuitka SideJITServer-main/SideJITServer/launch.py
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: SideJITServer-Windows
        path: SideJITServer-windows-x86_64.exe
